### ISSUE TITLE
Multiple worksheets

### ISSUE THREAD

**Issue by buddiebubba** [camptocamp/QGIS-SpreadSheetLayers#2]
Great plugin! The only downside so far: The created vrt is named after the filename. This way only one sheet is usable.
Using the filename / worksheetname combination would make them unique, making it possible working with multiple sheets.
Workaround now is renaming the vrt before adding the next worksheet.

**Comment by mwtoews** [comment]
I'm here to comment that this is an excellent plugin, and to point out this limitation. The .vrt file should be named (e.g.) `Boot1.xlsx.Sheet1.vrt`, and the fix is pretty simple:
```
--- a/widgets/SpreadsheetLayersDialog.py
+++ b/widgets/SpreadsheetLayersDialog.py
@@ -565,7 +565,7 @@
         return True

     def vrtPath(self):
-        return u'{}.vrt'.format(self.filePath())
+        return u'{}.{}.vrt'.format(self.filePath(), self.sheet())

     def samplePath(self):
         filename = u'{}.tmp.vrt'.format(os.path.basename(self.filePath()))
```
I've tested this with QGIS 2.16.1 on Windows x64 from OSGeo4W, and it works as expected.

Is a pull request welcome? I'm not too familiar with QGIS plugins, are there any other changes elsewhere that would be needed?
